import sdl,\
SDL_Init, 'SDL_Init',\
SDL_Quit, 'SDL_Quit',\
\
SDL_CreateWindow, 'SDL_CreateWindow',\
SDL_DestroyWindow, 'SDL_DestroyWindow',\
\
SDL_CreateRenderer, 'SDL_CreateRenderer',\
SDL_DestroyRenderer, 'SDL_DestroyRenderer',\
SDL_RenderPresent, 'SDL_RenderPresent',\
SDL_SetRenderDrawColor, 'SDL_SetRenderDrawColor',\
SDL_RenderClear, 'SDL_RenderClear',\
SDL_RenderFillRect, 'SDL_RenderFillRect',\
SDL_RenderDrawLine, 'SDL_RenderDrawLine',\;Renderer*, x1, y1, x2, y2
SDL_RenderCopy, 'SDL_RenderCopy', \
\
SDL_PollEvent, 'SDL_PollEvent',\
\
SDL_Delay, 'SDL_Delay',\
SDL_GetTicks, 'SDL_GetTicks',\
\
SDL_LoadBMP, 'SDL_LoadBMP',\
\
SDL_BlitUpper, 'SDL_BlitUpper',\
SDL_GetWindowSurface, 'SDL_GetWindowSurface',\
SDL_UpdateWindowSurface, 'SDL_UpdateWindowSurface',\
SDL_FreeSurface, 'SDL_FreeSurface',\
SDL_BlitScaled, 'SDL_BlitScaled', \
SDL_ConvertSurface, 'SDL_ConvertSurface', \
SDL_FillRect, 'SDL_FillRect', \
SDL_BlitScaled, 'SDL_BlitScaled',\
SDL_CreateTextureFromSurface, 'SDL_CreateTextureFromSurface', \
\
SDL_QueryTexture, 'SDL_QueryTexture', \
SDL_DestroyTexture, 'SDL_DestroyTexture', \
\
SDL_MapRGB, 'SDL_MapRGB'
        