IMG_INIT_JPG    = 0x00000001
IMG_INIT_PNG    = 0x00000002
IMG_INIT_TIF    = 0x00000004
IMG_INIT_WEBP   = 0x00000008
IMG_INIT_JXL    = 0x00000010
IMG_INIT_AVIF   = 0x00000020

SDL_RENDERER_SOFTWARE = 0x00000001  ;The renderer is a software fallback 
SDL_RENDERER_ACCELERATED = 0x00000002      ; The renderer uses hardware acceleration 
SDL_RENDERER_PRESENTVSYNC = 0x00000004    ;Present is synchronized  with the refresh rate 
SDL_RENDERER_TARGETTEXTURE = 0x00000008    ;The renderer supports rendering to textur

SDL_TEXTUREMODULATE_NONE = 0x00000000     
SDL_TEXTUREMODULATE_COLOR = 0x00000001    
 SDL_TEXTUREMODULATE_ALPHA = 0x00000002 

SDL_FLIP_NONE = 0x00000000,    ; Do not flip 
SDL_FLIP_HORIZONTAL = 0x00000001,  ;flip horizontally 
SDL_FLIP_VERTICAL = 0x00000002     ; flip verticall 
 
 
